-- ============================================================
-- MYLATINOLIST — LEGACY SEED v2 (DO NOT RUN ON mll-dev)
-- These inserts omit businesses.owner_id (NOT NULL → auth.users).
-- Use supabase/seed/seed-dev.mjs + seed_dev.sql instead.
-- ============================================================

INSERT INTO businesses (name, slug, category, phone, email, website, description, city, state, zip, emoji, bg_color, tags, plan, is_featured, rating, review_count, profile_completion, status) VALUES

-- ── HEALTH & WELLNESS ─────────────────────────────────────
('Salud y Vida Clinic',
 'salud-y-vida-clinic',
 'Health & Wellness',
 '(786) 555-0201',
 'info@saludyvida.com',
 'https://saludyvida.com',
 'Bilingual family medicine and preventive care clinic. Walk-ins welcome. Accepting most insurance plans including Medicaid.',
 'Miami', 'FL', '33125',
 '🏥', '#E8F8F1',
 '{"Bilingual","Family Medicine","Walk-ins"}',
 'featured', true, 4.8, 156, 92, 'active'),

('Dr. Carmen Reyes — Dentista',
 'dr-carmen-reyes-dentista',
 'Health & Wellness',
 '(956) 555-0244',
 'info@reyesdental.com',
 'https://reyesdental.com',
 'General and cosmetic dentistry with full bilingual staff. Payment plans available. Families welcome.',
 'McAllen', 'TX', '78501',
 '🦷', '#E8F8F1',
 '{"Cosmetic","Bilingual","Payment Plans"}',
 'pro', false, 4.9, 203, 88, 'active'),

-- ── REAL ESTATE ───────────────────────────────────────────
('Herrera Realty Group',
 'herrera-realty-group',
 'Real Estate',
 '(305) 555-0312',
 'info@herrerarealty.com',
 'https://herrerarealty.com',
 'Bilingual real estate team specializing in first-time homebuyers and investment properties across South Florida.',
 'Miami', 'FL', '33130',
 '🏠', '#FFF3E0',
 '{"First-time Buyers","Investment","Bilingual"}',
 'featured', true, 4.7, 89, 90, 'active'),

('Castillo Properties',
 'castillo-properties',
 'Real Estate',
 '(210) 555-0355',
 'info@castilloprop.com',
 null,
 'Residential and commercial property management serving the San Antonio metro area. 20+ years of experience.',
 'San Antonio', 'TX', '78205',
 '🏢', '#FFF3E0',
 '{"Property Mgmt","Commercial","Residential"}',
 'pro', false, 4.6, 44, 75, 'active'),

-- ── TECH ──────────────────────────────────────────────────
('TechLatino Solutions',
 'techlatino-solutions',
 'Tech',
 '(669) 555-0401',
 'info@techlatino.io',
 'https://techlatino.io',
 'Web design, app development, and IT support for small Latino businesses. Bilingual project management and affordable rates.',
 'San Jose', 'CA', '95101',
 '💻', '#EEF0FE',
 '{"Web Design","App Dev","IT Support"}',
 'pro', true, 4.8, 67, 85, 'active'),

('Conecta Digital Agency',
 'conecta-digital-agency',
 'Tech',
 '(737) 555-0422',
 'hola@conectadigital.com',
 'https://conectadigital.com',
 'Social media marketing, SEO, and digital advertising for Latino-owned businesses. We speak your language — literally.',
 'Austin', 'TX', '78701',
 '📱', '#EEF0FE',
 '{"Social Media","SEO","Marketing"}',
 'pro', false, 4.9, 112, 92, 'active'),

-- ── EDUCATION ─────────────────────────────────────────────
('Academia Bilingüe del Sur',
 'academia-bilingue-del-sur',
 'Education',
 '(623) 555-0501',
 'info@academiabilingue.com',
 'https://academiabilingue.com',
 'Bilingual tutoring center for K-12 students. Math, science, English, and Spanish language programs. After-school and weekend classes.',
 'Phoenix', 'AZ', '85003',
 '📚', '#FFF8E1',
 '{"K-12","Tutoring","Bilingual"}',
 'pro', false, 4.9, 178, 87, 'active'),

('Escuela de Música Rivera',
 'escuela-de-musica-rivera',
 'Education',
 '(214) 555-0533',
 'info@musicarivera.com',
 null,
 'Music school offering guitar, piano, violin, and voice lessons in English and Spanish. All ages welcome.',
 'Dallas', 'TX', '75201',
 '🎵', '#FFF8E1',
 '{"Guitar","Piano","All Ages"}',
 'free', false, 4.7, 56, 65, 'active'),

-- ── RETAIL ────────────────────────────────────────────────
('Tienda Latina NYC',
 'tienda-latina-nyc',
 'Retail',
 '(212) 555-0601',
 'info@tiendalatinanyc.com',
 'https://tiendalatinanyc.com',
 'Authentic Latin American grocery, fresh produce, imported goods, and specialty foods. Serving New York since 2005.',
 'New York', 'NY', '10001',
 '🛒', '#FCE4EC',
 '{"Grocery","Imported","Fresh Produce"}',
 'pro', true, 4.8, 321, 88, 'active'),

('Moda Latina Boutique',
 'moda-latina-boutique',
 'Retail',
 '(323) 555-0644',
 'hola@modalatina.com',
 'https://modalatina.com',
 'Contemporary Latina fashion boutique featuring independent designers from the US, Mexico, and Colombia. Custom quinceañera and wedding attire.',
 'Los Angeles', 'CA', '90015',
 '👗', '#FCE4EC',
 '{"Fashion","Quinceañera","Custom"}',
 'featured', true, 4.9, 144, 93, 'active'),

-- ── EVENTS ────────────────────────────────────────────────
('Fiestas Morales Events',
 'fiestas-morales-events',
 'Events',
 '(702) 555-0701',
 'info@fiestasmorales.com',
 'https://fiestasmorales.com',
 'Full-service event planning for quinceañeras, weddings, corporate events, and community gatherings. Bilingual coordinators.',
 'Las Vegas', 'NV', '89101',
 '🎉', '#F3E5F5',
 '{"Quinceañera","Weddings","Corporate"}',
 'featured', true, 5.0, 89, 95, 'active'),

('DJ Latino Mix',
 'dj-latino-mix',
 'Events',
 '(303) 555-0733',
 'booking@djlatiномix.com',
 null,
 'Professional DJ services for quinceañeras, weddings, and parties. Reggaeton, cumbia, salsa, merengue, and top 40.',
 'Denver', 'CO', '80201',
 '🎧', '#F3E5F5',
 '{"DJ","Weddings","Quinceañera"}',
 'free', false, 4.6, 38, 60, 'active'),

-- ── FOOD & DINING (more) ──────────────────────────────────
('Panadería El Sol',
 'panaderia-el-sol',
 'Food & Dining',
 '(312) 555-0801',
 'info@panaderiaelsol.com',
 null,
 'Traditional Mexican bakery open since 1998. Pan dulce, tres leches cakes, and custom quinceañera cakes baked fresh daily.',
 'Chicago', 'IL', '60608',
 '🥐', '#FAECE7',
 '{"Bakery","Pan Dulce","Custom Cakes"}',
 'pro', false, 4.9, 267, 82, 'active'),

('Tacos El Rancho',
 'tacos-el-rancho',
 'Food & Dining',
 '(480) 555-0844',
 'info@tacosrancho.com',
 'https://tacosrancho.com',
 'Authentic Sonoran-style tacos, burritos, and menudo. Family recipes passed down three generations. Catering available.',
 'Tempe', 'AZ', '85281',
 '🌮', '#FAECE7',
 '{"Tacos","Catering","Family Recipe"}',
 'pro', true, 4.8, 198, 86, 'active'),

-- ── CONSTRUCTION (more) ───────────────────────────────────
('Mendoza Landscaping & Design',
 'mendoza-landscaping-design',
 'Construction',
 '(619) 555-0901',
 'info@mendozalandscape.com',
 null,
 'Full-service landscaping, irrigation systems, hardscaping, and garden design. Residential and commercial. Licensed & insured.',
 'San Diego', 'CA', '92101',
 '🌿', '#FAEEDA',
 '{"Landscaping","Irrigation","Hardscape"}',
 'pro', false, 4.7, 73, 78, 'active');

-- ── ADD PRODUCTS FOR NEW BUSINESSES ───────────────────────
INSERT INTO products (business_id, seller_name, name, description, price, category, emoji, bg_color, rating, sales_count, status) VALUES

((SELECT id FROM businesses WHERE slug='panaderia-el-sol'),
 'Panadería El Sol',
 'Pan dulce assortment (12 pieces)',
 'Mixed dozen of our most popular pan dulce — conchas, cuernos, and polvorones. Perfect for family gatherings.',
 18.00, 'Food', '🥐', '#FAECE7', 4.9, 34, 'active'),

((SELECT id FROM businesses WHERE slug='panaderia-el-sol'),
 'Panadería El Sol',
 'Tres leches cake (whole)',
 'Classic tres leches cake, feeds 12-15. Custom decorations available with 48hr notice.',
 45.00, 'Food', '🎂', '#FAECE7', 5.0, 12, 'active'),

((SELECT id FROM businesses WHERE slug='tienda-latina-nyc'),
 'Tienda Latina NYC',
 'Imported chili pepper variety pack',
 'Assortment of dried Mexican chilis — ancho, mulato, pasilla, guajillo. 8oz total.',
 14.00, 'Food', '🌶️', '#FCE4EC', 4.8, 28, 'active'),

((SELECT id FROM businesses WHERE slug='moda-latina-boutique'),
 'Moda Latina Boutique',
 'Hand-embroidered blouse',
 'Authentic Oaxacan hand-embroidered blouse. Available in S, M, L, XL. Multiple color options.',
 78.00, 'Clothing', '👘', '#FCE4EC', 4.9, 15, 'active'),

((SELECT id FROM businesses WHERE slug='techlatino-solutions'),
 'TechLatino Solutions',
 'Business website starter package',
 '5-page bilingual website with contact form, Google Maps, and mobile optimization. Delivered in 2 weeks.',
 499.00, 'Tech', '🌐', '#EEF0FE', 5.0, 8, 'active');

-- ── ADD JOBS FOR NEW BUSINESSES ───────────────────────────
INSERT INTO jobs (business_id, company_name, title, description, city, state, salary_range, job_type, bilingual_required, emoji, emoji_bg, type_bg, type_color, status) VALUES

((SELECT id FROM businesses WHERE slug='salud-y-vida-clinic'),
 'Salud y Vida Clinic',
 'Medical receptionist — bilingual required',
 'Front desk reception, appointment scheduling, insurance verification. Spanish fluency required.',
 'Miami', 'FL', '$18–$22/hr', 'Full-time', true,
 '🏥', '#E8F8F1', '#E1F5EE', '#085041', 'active'),

((SELECT id FROM businesses WHERE slug='techlatino-solutions'),
 'TechLatino Solutions',
 'Junior web developer',
 'Build and maintain websites for Latino small businesses. React or Vue experience preferred. Remote-friendly.',
 'San Jose', 'CA', '$55K–$70K/yr', 'Full-time', false,
 '💻', '#EEF0FE', '#E6F1FB', '#0C447C', 'active'),

((SELECT id FROM businesses WHERE slug='tienda-latina-nyc'),
 'Tienda Latina NYC',
 'Store associate — Spanish required',
 'Customer service, stocking, and cashier duties. Spanish fluency required, knowledge of Latin products a plus.',
 'New York', 'NY', '$17–$20/hr', 'Part-time', true,
 '🛒', '#FCE4EC', '#FAEEDA', '#633806', 'active'),

((SELECT id FROM businesses WHERE slug='fiestas-morales-events'),
 'Fiestas Morales Events',
 'Event coordinator assistant',
 'Assist lead coordinators with quinceañera and wedding planning. Weekend availability required.',
 'Las Vegas', 'NV', '$20–$26/hr', 'Full-time', true,
 '🎉', '#F3E5F5', '#EEEDFE', '#3C3489', 'active'),

((SELECT id FROM businesses WHERE slug='herrera-realty-group'),
 'Herrera Realty Group',
 'Bilingual real estate agent',
 'Represent buyers and sellers in South Florida. Active FL real estate license required. Commission-based.',
 'Miami', 'FL', '$60K–$120K/yr', 'Full-time', true,
 '🏠', '#FFF3E0', '#FAEEDA', '#633806', 'active');
